// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtbhxnstepeybybvtaxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0Ymh4bnN0ZXBleWJ5YnZ0YXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDQxNTUsImV4cCI6MjA3NDYyMDE1NX0._IVwz_VCX7SdkMlmTboOsgzXvZRaO0vxp0_LE9omGnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});